### ISSUE TITLE
HAL from RPC example no longer works

### ISSUE THREAD

**Issue by Philio** [zfcampus/apigility-documentation#72]
https://github.com/zfcampus/apigility-documentation/blob/master/recipes/hal-from-rpc.md

Doesn't work any more for collections.

Error: A plugin by the name "hal" was not found in the plugin manager Zend\Mvc\Controller\PluginManager

**Comment by Philio** [comment]
Seems to work with an uppercase H:

`$this->getPluginManager()->get('Hal')->createCollection(...)`

**Comment by karborator** [comment]
Using  with upper case "Hal"

`Link from resource provided to ZF\Hal\Extractor\LinkExtractor::extract was incomplete; must contain a URL or a route`

**Comment by webimpress** [comment]
Fixes in #74.
